In [5]:
print("HELLO CAMELS!")

HELLO CAMELS!

In [6]:
import os
print(os.listdir())

['.ipynb_checkpoints', '01013500_lump_cida_forcing_leap.txt', '01013500_streamflow_qc.txt', 'day2_load_data.ipynb']

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("01013500_streamflow_qc.txt", sep="\t", skiprows=30, names=["basin", "year", "month", "day", "streamflow", "flag"])

In [9]:
df.head()

                            basin  year  month  day  streamflow  flag
0  01013500 1980 01 31   455.00 A   NaN    NaN  NaN         NaN   NaN
1  01013500 1980 02 01   445.00 A   NaN    NaN  NaN         NaN   NaN
2  01013500 1980 02 02   440.00 A   NaN    NaN  NaN         NaN   NaN
3  01013500 1980 02 03   425.00 A   NaN    NaN  NaN         NaN   NaN
4  01013500 1980 02 04   415.00 A   NaN    NaN  NaN         NaN   NaN

In [10]:
df.describe()

       year  month  day  streamflow  flag
count   0.0    0.0  0.0         0.0   0.0
mean    NaN    NaN  NaN         NaN   NaN
std     NaN    NaN  NaN         NaN   NaN
min     NaN    NaN  NaN         NaN   NaN
25%     NaN    NaN  NaN         NaN   NaN
50%     NaN    NaN  NaN         NaN   NaN
75%     NaN    NaN  NaN         NaN   NaN
max     NaN    NaN  NaN         NaN   NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12754 entries, 0 to 12753
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   basin       12754 non-null  object
 1   year        0 non-null      float64
 2   month       0 non-null      float64
 3   day         0 non-null      float64
 4   streamflow  0 non-null      float64
 5   flag        0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 598.0+ KB

#روز 2 تیر داده دبی حوضه 01013500 با پانداس بارگزاری شد

# داده حاوی مقادیر گمشده NaN هست
#هفته دوم تیر به این مورد رسیدگی خواهم کرد

In [13]:
# ساختن ستون تاریخ از سه ستون year, month, day
df["date"] = pd.to_datetime(df[["year", "month", "day"]])

In [14]:
df.head()

                            basin  year  month  day  streamflow  flag date
0  01013500 1980 01 31   455.00 A   NaN    NaN  NaN         NaN   NaN  NaT
1  01013500 1980 02 01   445.00 A   NaN    NaN  NaN         NaN   NaN  NaT
2  01013500 1980 02 02   440.00 A   NaN    NaN  NaN         NaN   NaN  NaT
3  01013500 1980 02 03   425.00 A   NaN    NaN  NaN         NaN   NaN  NaT
4  01013500 1980 02 04   415.00 A   NaN    NaN  NaN         NaN   NaN  NaT

In [15]:
# ببینیم چندتا NaT داریم
print(df["date"].isna().sum())

12754

In [17]:
df = df.dropna(subset=["date"])

In [18]:
df.head()

Empty DataFrame
Columns: [basin, year, month, day, streamflow, flag, date]
Index: []

In [19]:
len(df)

0

#برنامه 3 تیر
#ستون تاریخ ساخته شد
#تاریخ خای نا معتبر شناسایی و حذف شدند
# داده تمیز و آماده رسم نمودار